await page.goto('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login');
await page.getByPlaceholder('Username').click();
await page.getByPlaceholder('Username').fill('Admin');
await page.getByPlaceholder('Password').click();
await page.getByPlaceholder('Password').fill('admin123');
await page.getByRole('button', { name: 'Login' }).click();
await page.getByRole('img', { name: 'profile picture' }).click();
await page.getByRole('banner').getByText('manda user').click();
await page.getByRole('menuitem', { name: 'Logout' }).click();
await page.locator('.orangehrm-login-branding').click();